services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
