version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: task-management-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend-network
    command: >
      sh -c "npm run build && nginx -g 'daemon off;'"

networks:
  frontend-network:
    driver: bridge
